### ISSUE TITLE
Minor issue:  LICENSE file does not have a valid copyright

### ISSUE THREAD

**Issue by jearls** [Telmo/hiera-mysql-backend#8]
This is really minor, but I have no other way of contacting you.

Your `LICENSE` file includes a copyright notice of `Copyright (c) 2013 Roberto`.  Unless `Roberto` is your full legal name, this is not a valid copyright notice.

Unfortunately, this means I cannot use this software because it has to go through my company's legal department for review and approval, and they will not approve anything that has an invalid license file.

Any chance you can update the `LICENSE` file to have a proper copyright notice?

-- Johnson

**Comment by Telmo** [comment]
@jearls the LICENSE file has been updated. I know very well the pain of legal departments.

**Comment by ghost** [comment]
Thanks :)
